export const dataVideoCollection = [
  {
    id: 1,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 2,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 3,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 4,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 5,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 6,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
  {
    id: 7,
    url: 'https://www.youtube.com/watch?v=2kntnocgLfc',
    image: 'https://i.ytimg.com/vi/2kntnocgLfc/mqdefault.jpg',
    title: 'The Beach Chill Mix 🎵 Relaxing THE LAST OF US Part II Ambient Music',
    channelTitle: 'z3n Pnk',
    publishedAt: '2021-01-31T08:00:00Z',
    duration: 'PT1H1S',
    description: 'One hour of relaxing ambient music from The Last of Us Part I & II official soundtracks (OST).',
    tags: [
      { id: 13, name: 'Person' },
      { id: 23, name: 'Communication' },
      { id: 17, name: 'AI' },
      { id: 27, name: 'Xuxu' },
      { id: 11, name: 'Gato' },
      { id: 21, name: 'Television' },
    ],
  },
];

export default {
  dataVideoCollection,
};
