import { RoleType, Story } from '@src/types';

export const dataStories: Story[] = [
  {
    id: 1,
    title: 'After Life2',
    imageUrl: 'image1.jpg',
    user: {
      id: 1,
      firstName: 'Luciano',
      lastName: 'Frizzera',
      userName: 'lucaju@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Luciano Frizzera & Julia Salles',
    languageCode: 'en-CA',
    published: true,
    publishedDate: '2022-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 2,
    title: 'Sil 2',
    imageUrl: '',
    user: {
      id: 2,
      firstName: 'Julia',
      lastName: 'Salles',
      userName: 'julia.salles@chatstories.ca',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Julia Salles',
    languageCode: 'en-CA',
    published: false,
    publishedDate: '2022-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 3,
    title: 'Hey I',
    imageUrl: 'image6.jpg',
    user: {
      id: 1,
      firstName: 'Luciano',
      lastName: 'Frizzera',
      userName: 'lucaju@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Luciano Frizzera',
    languageCode: 'fr-CA',
    published: false,
    publishedDate: '2022-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 120,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 4,
    title: 'After Life',
    imageUrl: 'image2.jpg',
    user: {
      id: 3,
      firstName: 'Samia',
      lastName: 'Pedraça',
      userName: 'spddraca@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Samia Pedraça',
    languageCode: 'en-CA',
    published: false,
    publishedDate: '2021-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 5,
    title: 'The Post-Human 2',
    imageUrl: 'image3.png',
    user: {
      id: 3,
      firstName: 'Samia',
      lastName: 'Pedraça',
      userName: 'spddraca@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'The Bot',
    languageCode: 'en-CA',
    published: false,
    publishedDate: '2021-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 6,
    title: 'The Post-Human',
    imageUrl: '',
    user: {
      id: 2,
      firstName: 'Julia',
      lastName: 'Salles',
      userName: 'julia.salles@chatstories.ca',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'No one',
    languageCode: 'fr-CA',
    published: false,
    publishedDate: '2021-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 7,
    title: 'Circuits',
    imageUrl: 'image4.png',
    user: {
      id: 3,
      firstName: 'Samia',
      lastName: 'Pedraça',
      userName: 'spddraca@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'All of us',
    languageCode: 'en-CA',
    published: true,
    publishedDate: '2021-01-01T00:00:00',
    synopsis: '',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 8,
    title: 'Carbon',
    imageUrl: '',
    user: {
      id: 2,
      firstName: 'Julia',
      lastName: 'Salles',
      userName: 'julia.salles@chatstories.ca',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Class 2021',
    languageCode: 'en-CA',
    published: true,
    publishedDate: '2021-01-01T00:00:00',
    synopsis: '',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 9,
    title: 'SilbotAvatar',
    imageUrl: 'image5.png',
    user: {
      id: 3,
      firstName: 'Samia',
      lastName: 'Pedraça',
      userName: 'spddraca@gmail.com',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Luciano, Julia and Samia',
    languageCode: 'en-CA',
    published: true,
    publishedDate: '2020-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
  {
    id: 10,
    title: 'Zero Or One',
    imageUrl: '',
    user: {
      id: 2,
      firstName: 'Julia',
      lastName: 'Salles',
      userName: 'julia.salles@chatstories.ca',
      roleTypeId: RoleType.ADMIN,
    },
    author: 'Julia',
    languageCode: 'en-CA',
    published: true,
    publishedDate: '2020-01-01T00:00:00',
    synopsis:
      'Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. Doner rump pastrami chislic short loin. Ribeye corned beef spare ribs short ribs frankfurter cow leberkas picanha.',
    botAvatar: 'adb',
    botName: 'Daft Punk',
    botDelay: 100,
    botPersona:
      'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig short ribs ham hock, drumstick cow filet mignon sirloin. ',
  },
];

export const storyDefault: Omit<Story, 'id'> = {
  title: '',
  languageCode: 'en-CA',
  user: {
    id: 2,
    firstName: 'Julia',
    lastName: 'Salles',
    userName: 'julia.salles@chatstories.ca',
    roleTypeId: RoleType.ADMIN,
  },
  author: '',
  synopsis: '',
  imageUrl: '',
  published: false,
  publishedDate: '',
  botAvatar: '',
  botName: '',
  botPersona: '',
  botDelay: 120,
};

export const storyExample: Story = {
  id: 1,
  title: 'After Life',
  languageCode: 'en-CA',
  user: {
    id: 2,
    firstName: 'Julia',
    lastName: 'Salles',
    userName: 'julia.salles@chatstories.ca',
    roleTypeId: RoleType.ADMIN,
  },
  author: 'Julia Salles',
  synopsis: 'A history beyond this world',
  imageUrl: '/images/image1.jpg',
  published: true,
  publishedDate: '2022-01-01T00:00:00',
  botAvatar: 'adb',
  botName: 'Daft Punk',
  botPersona: 'A Duo Bacon ipsum dolor amet pastrami turducken fatback pig',
  botDelay: 100,
};

export default {
  dataStories,
  storyDefault,
  storyExample,
};
